=== bobmcwhirter/jboss-messaging/src/schemas/jbm-jms.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   targetNamespace="urn:jboss:messaging-jms"
   xmlns="urn:jboss:messaging-jms"
   elementFormDefault="qualified"
   attributeFormDefault="unqualified"
   version="1.0">
   
   <xsd:element name="deployment">
   	<xsd:complexType>
   		<xsd:sequence>
   			<xsd:element ref="connection-factory"
   				maxOccurs="unbounded" minOccurs="1">
   			</xsd:element>
   			<xsd:choice maxOccurs="unbounded" minOccurs="1">
   				<xsd:element ref="queue" maxOccurs="1"
   					minOccurs="1">
   				</xsd:element>
   				<xsd:element ref="topic" maxOccurs="1" minOccurs="1"></xsd:element>
   			</xsd:choice>
   		</xsd:sequence>
   	</xsd:complexType>
   </xsd:element>

   <xsd:element name="connection-factory">
   	<xsd:complexType>
   		<xsd:sequence>
            <xsd:choice>
            	<xsd:element ref="connector-ref" maxOccurs="1"
            		minOccurs="1">
            	</xsd:element>
            	<xsd:element name="discovery-group-ref" type="discovery-group-refType" maxOccurs="1" minOccurs="1"></xsd:element>
            </xsd:choice>
            <xsd:element name="entry" type="entryType"
   				maxOccurs="unbounded" minOccurs="1">
   			</xsd:element>
   			<xsd:element name="ping-period" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
            <xsd:element name="call-timeout" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="client-id" type="xsd:string"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="dups-ok-batch-size" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="transaction-batch-size" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="producer-window-size" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="producer-max-rate" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="consumer-window-size" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="consumer-max-rate" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="block-on-acknowledge" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="send-np-messages-synchronously" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="send-p-messages-synchronously" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="auto-group-id" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   			<xsd:element name="pre-acknowledge" type="xsd:boolean"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
   		</xsd:sequence>
   		<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
   	</xsd:complexType>
   </xsd:element>

    <xsd:element name="connector-ref" type="connector-refType"></xsd:element>

    <xsd:complexType name="connector-refType">
    	<xsd:attribute name="connector-name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="backup-connector-name" type="xsd:string" use="optional"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="entryType">
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="discovery-group-refType">
    	<xsd:attribute name="discovery-group-name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="queue" type="destinationType"></xsd:element>


    
    <xsd:complexType name="destinationType">
    	<xsd:sequence>
    		<xsd:element name="entry" type="entryType" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:ID" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="topic" type="destinationType"></xsd:element>
</xsd:schema>

=== bobmcwhirter/jboss-messaging/examples/jms/durable/config/jbm-jms.xml
<deployment xmlns="urn:jboss:messaging"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-jms.xsd ">
   <!--the connection factory used by the example-->
   <connection-factory name="ConnectionFactory">
      <connector-ref connector-name="netty"/>
      <entry name="ConnectionFactory"/>
      <entry name="XAConnectionFactory"/>
      <entry name="java:/ConnectionFactory"/>
      <entry name="java:/XAConnectionFactory"/>
   </connection-factory>

   <!--the topic used by the example-->
   <topic name="exampleTopic">
      <entry name="/topic/exampleTopic"/>
   </topic>

</deployment>

=== bobmcwhirter/jboss-messaging/examples/jms/client-side-load-balancing/server1/jbm-jms.xml
<deployment xmlns="urn:jboss:messaging"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-jms.xsd ">
   <!--the connection factory used by the example-->
   <connection-factory name="ConnectionFactory">
      <discovery-group-ref discovery-group-name="my-discovery-group"/>
      <entry name="ConnectionFactory"/>
      <entry name="XAConnectionFactory"/>
      <entry name="java:/ConnectionFactory"/>
      <entry name="java:/XAConnectionFactory"/>      
   </connection-factory>

   <!--the queue used by the example-->
   <queue name="exampleQueue">
      <entry name="/queue/exampleQueue"/>
   </queue>

</deployment>

=== bobmcwhirter/jboss-messaging/src/config/jbm-jms.xml
<deployment xmlns="urn:jboss:messaging" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-jms.xsd ">

   <connection-factory name="testConnectionFactory">
      <connector-ref connector-name="netty"/>
      <entry name="testConnectionFactory"/>
   </connection-factory>

   <connection-factory name="ConnectionFactory">
      <connector-ref connector-name="netty"/>
      <entry name="ConnectionFactory"/>
      <entry name="/ConnectionFactory"/>
      <entry name="/XAConnectionFactory"/>
      <entry name="java:/ConnectionFactory"/>
      <entry name="java:/XAConnectionFactory"/>
   </connection-factory>

   <connection-factory name="ServerAckConnectionFactory">
      <connector-ref connector-name="netty"/>
      <entry name="ServerAckConnectionFactory"/>
      <entry name="/ServerAckConnectionFactory"/>
      <entry name="/ServerAckXAConnectionFactory"/>
      <entry name="java:/ServerAckConnectionFactory"/>
      <entry name="java:/ServerAckXAConnectionFactory"/>
      <pre-acknowledge>true</pre-acknowledge>
   </connection-factory>

   <connection-factory name="ClusteredConnectionFactory">
      <connector-ref connector-name="netty" backup-connector-name="netty-backup"/>
      <entry name="/ClusteredConnectionFactory"/>
      <entry name="/ClusteredXAConnectionFactory"/>
      <entry name="java:/ClusteredConnectionFactory"/>
      <entry name="java:/ClusteredXAConnectionFactory"/>
   </connection-factory>
   
   <connection-factory name="ClusteredConnectionFactoryWithDiscovery">
      <discovery-group-ref discovery-group-name="dg-group1"/> 
      <entry name="/ClusteredConnectionFactory"/>
      <entry name="/ClusteredXAConnectionFactory"/>
      <entry name="java:/ClusteredConnectionFactory"/>
      <entry name="java:/ClusteredXAConnectionFactory"/>
   </connection-factory>

   <connection-factory name="MyExampleConnectionFactory">
      <connector-ref connector-name="netty"/>
      <entry name="/MyExampleConnectionFactory"/>
      <entry name="/acme/MyExampleConnectionFactoryDupe"/>
      <entry name="java:/xyz/CF1"/>
      <entry name="java:/connectionfactories/acme/connection_factory"/>
      <ping-period>5000</ping-period>
      <call-timeout>30000</call-timeout>
      <!-- You can specify the default Client ID to use for connections created using this factory -->
      <client-id>MyClientID</client-id>
      <!-- The batch size in bytes to use when using the DUPS_OK_ACKNOWLEDGE acknowledgement mode -->
      <dups-ok-batch-size>1048576</dups-ok-batch-size>
      <!-- The batch size in bytes to use when using transactional sessions -->
      <transaction-batch-size>1048576</transaction-batch-size>
      <!-- This is the send window size in bytes -->
      <producer-window-size>1048576</producer-window-size>
      <!-- This is the maximum producer send rate that will be applied when using rate based producer flow control -->
      <producer-max-rate>100</producer-max-rate>
      <!-- When using this ConnectionFactory, messages beyond this limit are considered largeMessages and will be sent using smaller packets -->
      <big-message-size>10240</big-message-size>
      <!-- This is the window size in bytes to use when using consumer window based flow control -->
      <consumer-window-size>1048576</consumer-window-size>
      <!-- This is the maximum producer send rate that will be applied when using rate based consumer flow control -->
      <consumer-max-rate>5000</consumer-max-rate>
      <!--Whether or not we use a blocking call when acknowledging a message-->
      <block-on-acknowledge>false</block-on-acknowledge>
      <!--Whether we send non persistent messages synchronously-->
      <send-np-messages-synchronously>true</send-np-messages-synchronously>
      <!--Whether we send persistent messages synchronously-->
      <send-p-messages-synchronously>true</send-p-messages-synchronously>
      <!--If true, any connections will automatically set a unique group id (per producer) on every message sent-->
      <auto-group-id>true</auto-group-id>
      <!--if true then the server will pre ack any message before delivery to a consumer-->
      <pre-acknowledge>false</pre-acknowledge>
   </connection-factory>

   <connection-factory name="TestInVMConnectionFactory">
      <connector-ref connector-name="in-vm"/>
      <entry name="/TestInVMConnectionFactory"/>
   </connection-factory>

   <connection-factory name="TestSSLConnectionFactory">
      <connector-ref connector-name="netty-ssl"/>
      <entry name="/TestSSLConnectionFactory"/>
   </connection-factory>

   <connection-factory name="TestHttpConnectionFactory">
      <connector-ref connector-name="netty-http"/>
      <entry name="/TestHttpConnectionFactory"/>
   </connection-factory>

   <connection-factory name="TestServletConnectionFactory">
      <connector-ref connector-name="netty-servlet"/>
      <entry name="/TestServletConnectionFactory"/>
   </connection-factory>

   <queue name="MyQueue">
      <entry name="MyQueue"/>
   </queue>
   <queue name="DLQ">
      <entry name="/queue/DLQ"/>
   </queue>
   <queue name="ExpiryQueue">
      <entry name="/queue/ExpiryQueue"/>
   </queue>
   <topic name="testTopic">
      <entry name="/topic/testTopic"/>
   </topic>
   <topic name="topic.A">
      <entry name="/topic/topicA"/>
   </topic>
   <topic name="topic.B">
      <entry name="/topic/topicB"/>
   </topic>
   <topic name="securedTopic">
      <entry name="/topic/securedTopic"/>
   </topic>
   <topic name="testDurableTopic">
      <entry name="/topic/testDurableTopic"/>
   </topic>
   <queue name="testQueue">
      <entry name="/queue/testQueue"/>
   </queue>
   <queue name="testGroupQueue">
      <entry name="/queue/testGroupQueue"/>
   </queue>
   <queue name="testPerfQueue">
      <entry name="/queue/testPerfQueue"/>
   </queue>
   <queue name="A">
      <entry name="/queue/A"/>
   </queue>
   <queue name="B">
      <entry name="/queue/B"/>
   </queue>
   <queue name="C">
      <entry name="/queue/C"/>
   </queue>
   <queue name="D">
      <entry name="/queue/D"/>
   </queue>
   <queue name="ex">
      <entry name="/queue/ex"/>
   </queue>
   <queue name="PrivateDLQ">
      <entry name="/queue/PrivateDLQ"/>
   </queue>
   <queue name="PrivateExpiryQueue">
      <entry name="/queue/PrivateExpiryQueue"/>
   </queue>
   <queue name="QueueWithOwnDLQAndExpiryQueue">
      <entry name="/queue/QueueWithOwnDLQAndExpiryQueue"/>
   </queue>
   <topic name="TopicWithOwnDLQAndExpiryQueue">
      <entry name="/topic/QueueWithOwnDLQAndExpiryQueue"/>
   </topic>
   <queue name="QueueWithOwnRedeliveryDelay">
      <entry name="/queue/QueueWithOwnRedeliveryDelay"/>
   </queue>
   <topic name="TopicWithOwnRedeliveryDelay">
      <entry name="/topic/TopicWithOwnRedeliveryDelay"/>
   </topic>
   <queue name="testDistributedQueue">
      <entry name="/queue/testDistributedQueue"/>
   </queue>
   <topic name="testDistributedTopic">
      <entry name="/topic/testDistributedTopic"/>
   </topic>

</deployment>
