=== bobmcwhirter/jboss-messaging/src/schemas/jbm-configuration.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="urn:jboss:messaging" xmlns="urn:jboss:messaging"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	version="1.0">

	<xsd:include schemaLocation="jbm-queues.xsd"></xsd:include>
	<xsd:element name="deployment">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="configuration" maxOccurs="1"
					minOccurs="1">
				</xsd:element>
				<xsd:element ref="settings" maxOccurs="1"
					minOccurs="0">
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="configuration">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="clustered" maxOccurs="1"
					minOccurs="0" />
				<xsd:element name="scheduled-max-pool-size"
					type="xsd:int" maxOccurs="1" minOccurs="0">
					<xsd:annotation>
						<xsd:documentation>
							Maximum number of threads to use for
							scheduled deliveries
						</xsd:documentation>
					</xsd:annotation>
				</xsd:element>
				<xsd:element name="security-enabled" type="xsd:boolean"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="security-invalidation-interval"
					type="period" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="wild-card-routing-enabled"
					type="xsd:boolean" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="management-address" type="xsd:string"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="management-notification-address"
					type="xsd:string" maxOccurs="1" minOccurs="0">
				</xsd:element>
                <xsd:element name="management-cluster-password"
                    type="xsd:string" maxOccurs="1" minOccurs="0">
                </xsd:element>				
                <xsd:element name="management-request-timeout"
                    type="period" maxOccurs="1" minOccurs="0">
                </xsd:element>              
				<xsd:element name="jmx-management-enabled"
					type="xsd:boolean" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="message-counter-enabled"
					type="xsd:boolean" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="connection-scan-period"
					type="period" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="connection-ttl-override"
					type="xsd:long" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="transaction-timeout" type="period"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="transaction-timeout-scan-period"
					type="period" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="message-expiry-scan-period"
					type="period" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="message-expiry-thread-priority"
					type="xsd:positiveInteger" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="id-cache-size" type="xsd:positiveInteger"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="persist-id-cache" type="xsd:boolean"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element ref="remoting-interceptors" maxOccurs="1"
					minOccurs="0">
				</xsd:element>
				<xsd:element name="queue-activation-timeout"
					type="xsd:unsignedLong" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="backup" type="xsd:boolean"
					maxOccurs="1" minOccurs="0">
				</xsd:element>				
				<xsd:element name="persist-delivery-count-before-delivery" type="xsd:boolean"
					maxOccurs="1" minOccurs="0">
				</xsd:element>				
				<xsd:element name="allow-route-when-no-bindings" type="xsd:boolean"
					maxOccurs="1" minOccurs="0">
				</xsd:element>				
				<xsd:element name="backup-connector-ref"
					type="backup-connectorType" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="connector" type="connectorType"
					minOccurs="0" maxOccurs="unbounded">
				</xsd:element>
				<xsd:element name="acceptor" type="acceptorType"
					minOccurs="1" maxOccurs="unbounded">
				</xsd:element>
				<xsd:element ref="broadcast-group" maxOccurs="unbounded"
					minOccurs="0">
				</xsd:element>
				<xsd:element ref="discovery-group" maxOccurs="unbounded"
					minOccurs="0">
				</xsd:element>
				<xsd:element name="divert" type="divertType"
					maxOccurs="unbounded" minOccurs="0">
				</xsd:element>
				<xsd:element name="queue" type="queueType"
					maxOccurs="unbounded" minOccurs="0">
				</xsd:element>
				<xsd:element name="bridge" type="bridgeType"
					maxOccurs="unbounded" minOccurs="0">
				</xsd:element>
				<xsd:element name="cluster-connection" type="clusterConnectionType"
					maxOccurs="unbounded" minOccurs="0">
				</xsd:element>
				<xsd:element name="paging-max-threads" type="xsd:positiveInteger"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="paging-directory" type="xsd:string"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="paging-global-watermark-size" type="xsd:positiveInteger"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="paging-max-global-size-bytes"
					type="xsd:unsignedLong" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="bindings-directory" type="xsd:string"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="create-bindings-dir"
					type="xsd:boolean" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="journal-directory" type="xsd:string"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="create-journal-dir"
					type="xsd:boolean" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="journal-type" type="journalType"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="journal-buffer-reuse-size"
					type="xsd:long" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="journal-sync-transactional"
					type="xsd:boolean" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="journal-sync-non-transactional"
					type="xsd:boolean" maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="journal-file-size" type="xsd:unsignedLong"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="journal-min-files" type="xsd:positiveInteger"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="journal-max-aio" type="xsd:positiveInteger"
					maxOccurs="1" minOccurs="0">
				</xsd:element>
				<xsd:element name="large-messages-directory"
					type="xsd:string" maxOccurs="1" minOccurs="0">
				</xsd:element>

			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="clustered" type="xsd:boolean"></xsd:element>

	<xsd:element name="local-bind-address" type="xsd:string"></xsd:element>

	<xsd:element name="local-bind-port" type="portRange"></xsd:element>

	<xsd:element name="group-address" type="xsd:string"></xsd:element>

	<xsd:element name="group-port" type="portRange"></xsd:element>

	<xsd:element name="broadcast-period" type="period"></xsd:element>

	<xsd:element name="connector-ref" type="connector-refType">
	</xsd:element>

	<xsd:element name="broadcast-group">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="local-bind-port" maxOccurs="1"
					minOccurs="0">
				</xsd:element>
				<xsd:element ref="group-address" maxOccurs="1"
					minOccurs="1">
				</xsd:element>
				<xsd:element ref="group-port" maxOccurs="1"
					minOccurs="1">
				</xsd:element>
				<xsd:element ref="broadcast-period" maxOccurs="1"
					minOccurs="0">
				</xsd:element>
				<xsd:element ref="connector-ref" maxOccurs="unbounded"
					minOccurs="0">
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:ID" use="required"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="refresh-timeout" type="period"></xsd:element>

	<xsd:element name="discovery-group">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="group-address" maxOccurs="1"
					minOccurs="1">
				</xsd:element>
				<xsd:element ref="group-port" maxOccurs="1"
					minOccurs="1">
				</xsd:element>
				<xsd:element ref="refresh-timeout" maxOccurs="1"
					minOccurs="0">
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:ID" use="required"></xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="discovery-group-ref">
		<xsd:complexType>
			<xsd:attribute name="discovery-group-name"
				type="xsd:IDREF">
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="connector-refType">
		<xsd:attribute name="connector-name" type="xsd:IDREF"
			use="required">
		</xsd:attribute>
		<xsd:attribute name="backup-connector-name" type="xsd:IDREF"
			use="optional">
		</xsd:attribute>
	</xsd:complexType>

	<xsd:element name="remoting-interceptors">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="class-name" type="xsd:string"
					maxOccurs="unbounded" minOccurs="1">
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="paramType">
		<xsd:attribute name="key" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="value" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="type" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="String"></xsd:enumeration>
					<xsd:enumeration value="Integer"></xsd:enumeration>
					<xsd:enumeration value="Long"></xsd:enumeration>
					<xsd:enumeration value="Boolean"></xsd:enumeration>
					<xsd:enumeration value="Float"></xsd:enumeration>
					<xsd:enumeration value="Double"></xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="connectorType">
		<xsd:sequence>
			<xsd:element name="factory-class" type="xsd:string"
				minOccurs="1" maxOccurs="1">
			</xsd:element>
			<xsd:element name="param" type="paramType"
				maxOccurs="unbounded" minOccurs="0">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:ID" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="acceptorType">
		<xsd:sequence>
			<xsd:element name="factory-class" type="xsd:string"
				minOccurs="1" maxOccurs="1">
			</xsd:element>
			<xsd:element name="param" type="paramType"
				maxOccurs="unbounded" minOccurs="0">
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="optional"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="bridgeType">	   
		<xsd:sequence>
			<xsd:element name="queue-name" type="xsd:string"
				maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="forwarding-address" type="xsd:string"
				maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="filter" type="filterType" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="transformer-class-name" type="xsd:string"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="retry-interval" type="period"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="retry-interval-multiplier"
				type="xsd:double" maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="reconnect-attempts"
				type="xsd:nonNegativeInteger" maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="failover-on-server-shutdown"
				type="xsd:boolean" maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="use-duplicate-detection"
				type="xsd:boolean" maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:choice>
				<xsd:element name="connector-ref"
					type="connector-refType" minOccurs="1" maxOccurs="1">
				</xsd:element>
				<xsd:element name="disccovery-group-ref" minOccurs="1"
					maxOccurs="1">
					<xsd:complexType>
						<xsd:attribute name="discovery-group-name"
							type="xsd:IDREF" use="required">
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
		</xsd:sequence>	
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>	
	</xsd:complexType>
	
   <xsd:complexType name="clusterConnectionType">      
		<xsd:sequence>
			<xsd:element name="address" type="xsd:string"
				maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="retry-interval" type="period"
				maxOccurs="1" minOccurs="0">
			</xsd:element>			
			<xsd:element name="use-duplicate-detection"
				type="xsd:boolean" maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="forward-when-no-consumers"
				type="xsd:boolean" maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="max-hops"
				type="xsd:positiveInteger" maxOccurs="1" minOccurs="0">
			</xsd:element>
			
			<xsd:choice>
				<xsd:element name="connector-ref"
					type="connector-refType" minOccurs="1" maxOccurs="unbounded">
				</xsd:element>
				<xsd:element name="discovery-group-ref" minOccurs="1"
					maxOccurs="1">
					<xsd:complexType>
						<xsd:attribute name="discovery-group-name"
							type="xsd:IDREF" use="required">
						</xsd:attribute>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="divertType">	   
		<xsd:sequence>
			<xsd:element name="routing-name" type="xsd:string"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="address" type="xsd:string" maxOccurs="1"
				minOccurs="1">
			</xsd:element>
			<xsd:element name="forwarding-address" type="xsd:string"
				maxOccurs="1" minOccurs="1">
			</xsd:element>
			<xsd:element name="filter" type="filterType" maxOccurs="1"
				minOccurs="0">
			</xsd:element>
			<xsd:element name="transformer-class-name" type="xsd:string"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
			<xsd:element name="exclusive" type="xsd:boolean"
				maxOccurs="1" minOccurs="0">
			</xsd:element>
		</xsd:sequence>	
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>	
	</xsd:complexType>

	<xsd:simpleType name="journalType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ASYNCIO"></xsd:enumeration>
			<xsd:enumeration value="NIO"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:complexType name="backup-connectorType">
		<xsd:attribute name="connector-name" type="xsd:IDREF"
			use="required">
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="filterType">
		<xsd:attribute name="string" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>


	<xsd:simpleType name="portRange">
		<xsd:restriction base="xsd:int">
		      <xsd:minExclusive value="1024"></xsd:minExclusive>
		</xsd:restriction>
	</xsd:simpleType>

    <xsd:simpleType name="period">
        <xsd:restriction base="xsd:unsignedLong"></xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== bobmcwhirter/jboss-messaging/examples/jms/jmx/server0/jbm-configuration.xml
<configuration xmlns="urn:jboss:messaging"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-configuration.xsd">

    <!-- true to expose JBoss Messaging resources through JMX -->
    <jmx-management-enabled>true</jmx-management-enabled>

   <!-- Connectors -->
   <connectors>
      <connector name="netty">
         <factory-class>org.jboss.messaging.integration.transports.netty.NettyConnectorFactory</factory-class>
         <param key="jbm.remoting.netty.port" value="5445" type="Integer"/>
      </connector>
   </connectors>
   
   <!-- Acceptors -->
   <acceptors>
      <acceptor name="netty">
         <factory-class>org.jboss.messaging.integration.transports.netty.NettyAcceptorFactory</factory-class>
         <param key="jbm.remoting.netty.port" value="5445" type="Integer"/>
      </acceptor>
   </acceptors>

   <!-- Other config -->

   <journal-min-files>2</journal-min-files>

</configuration>

=== bobmcwhirter/jboss-messaging/tests/config/ConfigurationTest-full-config.xml
<deployment xmlns="urn:jboss:messaging" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:jboss:messaging ../../src/schemas/jbm-configuration.xsd ">
   <configuration>
      <clustered>true</clustered>
      <scheduled-max-pool-size>12345</scheduled-max-pool-size>        
      <require-destinations>false</require-destinations>
      <security-enabled>false</security-enabled>
      <security-invalidation-interval>5423</security-invalidation-interval>
      <wild-card-routing-enabled>true</wild-card-routing-enabled>
      <management-address>Giraffe</management-address>
      <management-notification-address>Whatever</management-notification-address>
      <jmx-management-enabled>false</jmx-management-enabled>
      <message-counter-enabled>true</message-counter-enabled>
      <connection-scan-period>6543</connection-scan-period>
      <connection-ttl-override>12345</connection-ttl-override>
      <transaction-timeout>98765</transaction-timeout>
      <transaction-timeout-scan-period>56789</transaction-timeout-scan-period>
      <message-expiry-scan-period>10111213</message-expiry-scan-period>
      <message-expiry-thread-priority>8</message-expiry-thread-priority>
      <id-cache-size>127</id-cache-size>
      <persist-id-cache>true</persist-id-cache>
      <remoting-interceptors>
         <class-name>org.jboss.messaging.tests.unit.core.config.impl.TestInterceptor1</class-name>
         <class-name>org.jboss.messaging.tests.unit.core.config.impl.TestInterceptor2</class-name>
      </remoting-interceptors>
      <queue-activation-timeout>12456</queue-activation-timeout>
      <backup>true</backup>
      <backup-connector-ref connector-name="backup-connector"/>
      <connector name="connector">
         <factory-class>org.jboss.messaging.tests.unit.core.config.impl.TestConnectorFactory1</factory-class>
         <param key="d_mykey1" value="d_foovalue1" type="String"/>
         <param key="d_mykey2" value="6000" type="Long"/>
         <param key="d_mykey3" value="60" type="Integer"/>
         <param key="d_mykey4" value="d_foovalue4" type="String"/>      
      </connector>
      <connector name="backup-connector">
         <factory-class>org.jboss.messaging.tests.unit.core.config.impl.TestConnectorFactory1</factory-class>
         <param key="c_mykey1" value="c_foovalue1" type="String"/>
         <param key="c_mykey2" value="6000" type="Long"/>
         <param key="c_mykey3" value="60" type="Integer"/>
         <param key="c_mykey4" value="c_foovalue4" type="String"/>      
      </connector>
      <acceptor name="acceptor1">
         <factory-class>org.jboss.messaging.tests.unit.core.config.impl.TestAcceptorFactory1</factory-class>           
         <param key="a_mykey1" value="a_foovalue1" type="String"/>
         <param key="a_mykey2" value="1234567" type="Long"/>
         <param key="a_mykey3" value="123" type="Integer"/>
         <param key="a_mykey4" value="a_foovalue4" type="String"/>                     
      </acceptor>
	  <acceptor name="acceptor2">
	      <factory-class>org.jboss.messaging.tests.unit.core.config.impl.TestAcceptorFactory2</factory-class>           
	      <param key="b_mykey1" value="b_foovalue1" type="String"/>
	      <param key="b_mykey2" value="7654321" type="Long"/>
	      <param key="b_mykey3" value="321" type="Integer"/>
	      <param key="b_mykey4" value="b_foovalue4" type="String"/>            
	   </acceptor>
	  <broadcast-group name="bg1">
	     <local-bind-address>127.0.0.1</local-bind-address>
	     <local-bind-port>10999</local-bind-port>
	     <group-address>192.168.0.120</group-address>
	     <group-port>11999</group-port>
         <broadcast-period>12345</broadcast-period>
         <connector-ref connector-name="connector"/>
	  </broadcast-group>
      <broadcast-group name="bg2">
         <local-bind-address>127.0.0.1</local-bind-address>
         <local-bind-port>10999</local-bind-port>
         <group-address>192.168.0.120</group-address>
         <group-port>11999</group-port>
         <broadcast-period>12345</broadcast-period>
         <connector-ref connector-name="connector"/>
      </broadcast-group>
      <discovery-group name="dg1">
         <group-address>192.168.0.121</group-address>
         <group-port>11999</group-port>
         <refresh-timeout>12345</refresh-timeout>
      </discovery-group>
      <discovery-group name="dg2">
         <group-address>192.168.0.121</group-address>
         <group-port>11999</group-port>
         <refresh-timeout>12345</refresh-timeout>
      </discovery-group>
      <divert name="divert1">
         <unique-name>unique-name1</unique-name>
         <routing-name>routing-name1</routing-name>
         <address>address1</address>
         <forwarding-address>forwarding-addres1</forwarding-address>
         <filter string="speed > 88"/>
         <transformer-class-name>org.foo.Transformer</transformer-class-name>
         <exclusive>true</exclusive>
      </divert>
      <divert name="divert2">
         <unique-name>unique-name2</unique-name>
         <routing-name>routing-name2</routing-name>
         <address>address2</address>
         <forwarding-address>forwarding-addres2</forwarding-address>
         <filter string="speed > 88"/>
         <transformer-class-name>org.foo.Transformer</transformer-class-name>
         <exclusive>false</exclusive>
      </divert>
      <queue name="foo" address="bar" filter="color = 'red'" durable="false" />
      <queue name="foo2" address="bar2" filter="color = 'red'" durable="false" />
      <bridge name="bridge">
          <queue-name>foo</queue-name>
          <forwarding-address>bridge-forwarding-address</forwarding-address>
          <filter string="sku > 1"/>
          <max-batch-size>124</max-batch-size>
          <max-batch-time>123456</max-batch-time>
          <transformer-class-name>org.foo.BridgeTransformer</transformer-class-name>
          <retry-interval>3</retry-interval>
          <retry-interval-multiplier>0.2</retry-interval-multiplier>
          <max-retries-before-failover>2</max-retries-before-failover>
          <max-retries-after-failover>5</max-retries-after-failover>
          <use-duplicate-detection>true</use-duplicate-detection>
          <connector-ref connector-name="connector"/>
      </bridge>
      <bridge name="bridge2">
          <queue-name>foo2</queue-name>
          <forwarding-address>bridge-forwarding-address</forwarding-address>
          <filter string="sku > 1"/>
          <disccovery-group-ref discovery-group-name="dg1"/>
      </bridge>

      <paging-max-threads>2</paging-max-threads>
      <paging-directory>pagingdir</paging-directory>
      <paging-default-size>123</paging-default-size>
      <paging-max-global-size-bytes>4567</paging-max-global-size-bytes>
      <bindings-directory>somedir</bindings-directory>
      <create-bindings-dir>false</create-bindings-dir>
      <journal-directory>somedir2</journal-directory>
      <create-journal-dir>false</create-journal-dir>
      <journal-type>NIO</journal-type>
      <journal-buffer-reuse-size>128</journal-buffer-reuse-size>
      <journal-sync-transactional>false</journal-sync-transactional>      
      <journal-sync-non-transactional>true</journal-sync-non-transactional>
      <journal-file-size>12345678</journal-file-size>
      <journal-min-files>100</journal-min-files>
      <journal-max-aio>56546</journal-max-aio>
      <large-messages-directory>largemessagesdir</large-messages-directory>
   </configuration>
   
   <settings>
    <queue name="foo3" address="bar" />
   </settings>

</deployment>

=== bobmcwhirter/jboss-messaging/examples/jms/clustered-queue/config/clustered-queue-example-configuration1.xml
<deployment xmlns="urn:jboss:messaging"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-configuration.xsd">
   <configuration>

      <clustered>true</clustered>

      <!-- Connectors -->
      
      <connector name="netty-connector">
         <factory-class>org.jboss.messaging.integration.transports.netty.NettyConnectorFactory</factory-class>
	 <param key="jbm.remoting.netty.port" value="5446" type="Integer"/>
      </connector>
      
      <!-- Acceptors -->
      
      <acceptor name="netty-acceptor">
	 <factory-class>org.jboss.messaging.integration.transports.netty.NettyAcceptorFactory</factory-class>
	 <param key="jbm.remoting.netty.port" value="5446" type="Integer"/>
      </acceptor>
      
      <!-- Clustering configuration -->
      
      <broadcast-group name="my-broacast-group">
	 <group-address>231.7.7.7</group-address>
	 <group-port>9876</group-port>
	 <broadcast-period>100</broadcast-period>
	 <connector-ref connector-name="netty-connector"/>
      </broadcast-group>
      
      <discovery-group name="my-discovery-group">
	 <group-address>231.7.7.7</group-address>
	 <group-port>9876</group-port>
	 <refresh-timeout>10000</refresh-timeout>
      </discovery-group>
      
      <cluster-connection name="my-cluster">
	 <address>jms</address>
	 <retry-interval>500</retry-interval>
	 <use-duplicate-detection>true</use-duplicate-detection>
	 <forward-when-no-consumers>true</forward-when-no-consumers>
	 <max-hops>1</max-hops>
	 <discovery-group-ref discovery-group-name="my-discovery-group"/>
      </cluster-connection>
      
      <!-- Other config -->
      
      <paging-directory>server1/data/paging</paging-directory>

      <bindings-directory>server1/data/bindings</bindings-directory>

      <journal-directory>server1/data/journal</journal-directory>
     
      <journal-min-files>2</journal-min-files>

      <large-messages-directory>server1/data/largeMessages</large-messages-directory>
      
   </configuration>

</deployment>
