=== bobmcwhirter/jboss-messaging/src/schemas/jbm-queues.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   targetNamespace="urn:jboss:messaging"
   xmlns="urn:jboss:messaging"
   elementFormDefault="qualified"
   attributeFormDefault="unqualified"
   version="1.0">
   
   <xsd:element name="settings">
   	<xsd:complexType>
   		<xsd:sequence>
   			<xsd:element ref="security" maxOccurs="unbounded"
   				minOccurs="0">
   			</xsd:element>
   			<xsd:element ref="queue-settings" maxOccurs="unbounded"
   				minOccurs="0">
   			</xsd:element>
            <xsd:element ref="queue" maxOccurs="unbounded"
                minOccurs="0">
            </xsd:element>
   		</xsd:sequence>
   	</xsd:complexType>
   </xsd:element>

   <xsd:element name="permission">
   	<xsd:complexType>
   		<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
   		<xsd:attribute name="roles" type="xsd:string" use="required"></xsd:attribute>
   	</xsd:complexType>
   </xsd:element>

   <xsd:element name="security">
   	<xsd:complexType>
   		<xsd:sequence>
   			<xsd:element ref="permission" maxOccurs="unbounded" minOccurs="1"></xsd:element>
   		</xsd:sequence>
            <xsd:attribute name="match" type="xsd:string" use="required"></xsd:attribute>
        </xsd:complexType>
   </xsd:element>

   <xsd:element name="queue-settings" type="queue-settingsType"></xsd:element>

   <xsd:complexType name="queue-settingsType">
   	<xsd:sequence>
        <xsd:element name="clustered" type="xsd:boolean"
            maxOccurs="1" minOccurs="0">
        </xsd:element>
   		<xsd:element name="dead-letter-address" type="xsd:string"
   			maxOccurs="1" minOccurs="0">
   		</xsd:element>
        <xsd:element name="expiry-address" type="xsd:string"
            maxOccurs="1" minOccurs="0">
        </xsd:element>
        <xsd:element name="redelivery-delay" type="xsd:long"
            maxOccurs="1" minOccurs="0">
        </xsd:element>
        <xsd:element name="max-size-bytes" type="xsd:long"
            maxOccurs="1" minOccurs="0">
        </xsd:element>
        <xsd:element name="page-size-bytes" type="xsd:long"
            maxOccurs="1" minOccurs="0">
        </xsd:element>
        <xsd:element name="drop-messages-when-full" type="xsd:boolean"
            maxOccurs="1" minOccurs="0">
        </xsd:element>
        <xsd:element name="distribution-policy-class" type="xsd:string"
            maxOccurs="1" minOccurs="0">
        </xsd:element>
        <xsd:element name="message-counter-history-day-limit" type="xsd:int"
            maxOccurs="1" minOccurs="0">
        </xsd:element>
   	</xsd:sequence>
   	<xsd:attribute name="match" type="xsd:string" use="required"></xsd:attribute>
   </xsd:complexType>   
   
      <xsd:element name="queue" type="queueType"></xsd:element>
   
    <xsd:complexType name="queueType">
        <xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="address" type="xsd:string"
            use="required">
        </xsd:attribute>
        <xsd:attribute name="filter" type="xsd:string" use="optional"></xsd:attribute>
        <xsd:attribute name="durable" type="xsd:boolean"
            use="optional">
        </xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== bobmcwhirter/jboss-messaging/examples/jms/security/server0/jbm-queues.xml
<settings xmlns="urn:jboss:messaging"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-queues.xsd ">

   <!-- any user can have full control of generic topics -->
   <security match="jms.topic.#">
      <permission type="createDurableQueue" roles="user"/>
      <permission type="deleteDurableQueue" roles="user"/>
      <permission type="createTempQueue" roles="user"/>
      <permission type="deleteTempQueue" roles="user"/>
      <permission type="send" roles="user"/>
      <permission type="consume" roles="user"/>
   </security>

   <security match="jms.topic.news.europe.#">
      <permission type="createDurableQueue" roles="user"/>
      <permission type="deleteDurableQueue" roles="user"/>
      <permission type="createTempQueue" roles="user"/>
      <permission type="deleteTempQueue" roles="user"/>
      <permission type="send" roles="europe-user"/>
      <permission type="consume" roles="news-user"/>
   </security>

   <security match="jms.topic.news.us.#">
      <permission type="createDurableQueue" roles="user"/>
      <permission type="deleteDurableQueue" roles="user"/>
      <permission type="createTempQueue" roles="user"/>
      <permission type="deleteTempQueue" roles="user"/>
      <permission type="send" roles="us-user"/>
      <permission type="consume" roles="news-user"/>
   </security>

</settings>

=== bobmcwhirter/jboss-messaging/examples/jms/paging/config/jbm-queues.xml
<settings xmlns="urn:jboss:messaging"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-queues.xsd ">

   <!--security for example queue-->
   <security match="jms.queue.exampleQueue">
      <permission type="createDurableQueue" roles="guest"/>
      <permission type="deleteDurableQueue" roles="guest"/>
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>
   
   <security match="jms.queue.pagingQueue">
      <permission type="createDurableQueue" roles="guest"/>
      <permission type="deleteDurableQueue" roles="guest"/>
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>
   
   <address-settings match="jms.queue.pagingQueue">
      <max-size-bytes>100000</max-size-bytes>
      <page-size-bytes>20000</page-size-bytes>
   </address-settings>

</settings>

=== bobmcwhirter/jboss-messaging/examples/jms/expiry/config/jbm-queues.xml
<settings xmlns="urn:jboss:messaging"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-queues.xsd ">

   <!--security for example queue-->
   <security match="queuejms.exampleQueue">
      <permission type="createDurableQueue" roles="guest"/>
      <permission type="deleteDurableQueue" roles="guest"/>
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>

   <!--security for dead letter queue-->
   <security match="queuejms.expiryQueue">
      <permission type="createDurableQueue" roles="guest"/>
      <permission type="deleteDurableQueue" roles="guest"/>
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>

   <!--override the expiry address for the example-->
   <address-settings match="queuejms.exampleQueue">
      <expiry-address>queuejms.expiryQueue</expiry-address>
   </address-settings>

</settings>

=== bobmcwhirter/jboss-messaging/src/config/stand-alone/non-clustered/jbm-queues.xml
<settings xmlns="urn:jboss:messaging" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-queues.xsd ">

   <!--  management address -->
   <security match="jbm.management">
      <!--  only the admin role can interact with the management address  -->
      <permission type="consume" roles="admin"/>
      <permission type="send" roles="admin"/>
      <permission type="manage" roles="admin"/>
   </security>
<!--example queue or topic configuration-->
   <!--<security match="jms.queue.#">
      <permission type="consume" roles="guest,publisher"/>
      <permission type="send" roles="guest,publisher"/>
   </security>-->
   <!--<security match="jms.topic.#">
      <permission type="consume" roles="guest,publisher"/>
      <permission type="send" roles="guest,publisher"/>
   </security>-->

   <!-- example temp queue or topic configuration -->
   <!--<security match="jms.tempqueue.#">
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>

   <security match="jms.temptopic.#">
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>-->

   <!--default security to catch all-->
   <security match="#">
      <permission type="createDurableQueue" roles="guest"/>
      <permission type="deleteDurableQueue" roles="guest"/>
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>

   <!--default for catch all-->
   <address-settings match="#">
      <clustered>false</clustered>
      <dead-letter-address>jms.queue.DLQ</dead-letter-address>
      <expiry-address>jms.queue.ExpiryQueue</expiry-address>
      <redelivery-delay>0</redelivery-delay>
      <max-size-bytes>-1</max-size-bytes>
      <page-size-bytes>10485760</page-size-bytes>
      <distribution-policy-class>org.jboss.messaging.core.server.impl.RoundRobinDistributor</distribution-policy-class>
      <message-counter-history-day-limit>10</message-counter-history-day-limit>
   </address-settings>
</settings>

=== bobmcwhirter/jboss-messaging/examples/javaee/mdb/config/jbm-queues.xml
<settings xmlns="urn:jboss:messaging" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-queues.xsd ">

   <security match="jms.queue.testQueue">
      <permission type="consume" roles="guest,publisher"/>
      <permission type="send" roles="guest,publisher"/>
   </security>

   <!--default for catch all-->
   <address-settings match="#">
      <clustered>false</clustered>
      <dead-letter-address>jms.queue.DLQ</dead-letter-address>
      <expiry-address>jms.queue.ExpiryQueue</expiry-address>
      <redelivery-delay>0</redelivery-delay>
      <max-size-bytes>-1</max-size-bytes>
      <page-size-bytes>10485760</page-size-bytes>
      <distribution-policy-class>org.jboss.messaging.core.server.impl.RoundRobinDistributor</distribution-policy-class>
      <message-counter-history-day-limit>10</message-counter-history-day-limit>
   </address-settings>
</settings>

=== bobmcwhirter/jboss-messaging/examples/jms/common/config/jbm-queues.xml
<settings xmlns="urn:jboss:messaging" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="urn:jboss:messaging ../schemas/jbm-queues.xsd ">

   <!--  manangement address -->
   <security match="jbm.admin.management">
      <!--  only the admin role can interact with the management address  -->
      <permission type="consume" roles="admin"/>
      <permission type="send" roles="admin"/>
      <permission type="createDurableQueue" roles="admin"/>
      <permission type="deleteDurableQueue" roles="admin"/>
      <permission type="createTempQueue" roles="admin"/>
      <permission type="deleteTempQueue" roles="admin"/>
      <permission type="manage" roles="admin"/>
   </security>
   
   <security match="topicjms.exampleTopic">
      <permission type="createDurableQueue" roles="durpublisher"/>
      <permission type="deleteDurableQueue" roles="durpublisher"/>
      <permission type="consume" roles="guest,publisher,durpublisher"/>
      <permission type="send" roles="guest,publisher,durpublisher"/>
   </security>

   <security match="queuejms.exampleQueue">
      <permission type="consume" roles="guest,publisher"/>
      <permission type="send" roles="guest,publisher"/>
   </security>

   <security match="queuetempjms.*">
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>

   <security match="topictempjms.*">
      <permission type="createTempQueue" roles="guest"/>
      <permission type="deleteTempQueue" roles="guest"/>
      <permission type="consume" roles="guest"/>
      <permission type="send" roles="guest"/>
   </security>

   <!--default security to catch all-->
   <security match="#">
      <permission type="createDurableQueue" roles="guest,def"/>
      <permission type="deleteDurableQueue" roles="guest,def"/>
      <permission type="createTempQueue" roles="guest,def"/>
      <permission type="deleteTempQueue" roles="guest,def"/>
      <permission type="consume" roles="guest,def"/>
      <permission type="send" roles="guest,def"/>
   </security>

</settings>
